# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0006_datastore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='filter_name',
            field=models.CharField(default='enter filter name', max_length=100),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='table_name',
            field=models.CharField(default='enter table name', max_length=100),
        ),
    ]
